export const messages = {
  required: "{attribute} is required",
  email: "{attribute} is not a valid email",
  alpha: "{attribute} must only contain alphabet characters",
  numeric: "{attribute} must only contain numeric characters",
  minLength: "{attribute} requires min length",
  maxLength: "{attribute} exceeds max length",
  minValue: " {attribute} requires min length",
  maxValue: "{attribute} exceeds max value",
  between: "{attribute} out of bounds",
  alphaNum: "{attribute} must have just letters or numbers",
  alphaExtra: "{attribute} has invalid characters",
  alphaNumExtra: "{attribute} has invalid characters",
  alphaNumericHashtag: "{attribute} invalid",
  stateValid: "NY is the only valid state",
  validLength: "{attribute} has an invalid length",
  inArray: "please choose a valid value for {attribute}",
  unique: "{attribute} must be unique",
  minLengthTime: "end time must be later than the start time",
  dateOfActivityMinValue: "date of activity must be within 2 years",
  endTimeRequired: "Please select an end time that is later than start time",
  requiredTrue: "This field is required to be true"
};
export const attributes = {
  // maps form keys to actual field names
  nyeisid: "nyeisid",
  isOutsideCase: "is outside case",
  referralDate: "ei referral date",
  eIReferrals: "ei referral list",
  firstName: "first name",
  lastName: "last name",
  gender: "gender",
  streetAddress: "street address",
  streetAddressLine2: "apartment",
  city: "city",
  state: "state",
  zipCode: "zip code",
  dob: "DOB",
  physicianName: "physician name",
  physicianPhone: "physician phone",
  caregiverFirstName: "caregiver first name",
  caregiverLastName: "caregiver last name",
  caregiverRelationship: "caregiver relationship",
  clientLanguages: "client languages",
  phoneNumbers: "Phone Numbers",
  number: "number",
  phoneType: "phone type",
  isPrimary: "is primary"
  //   Email: 'Email',
  //   SocialSecurity: 'Social Security',
  //   Discpline: 'Discipline',
  //   NPINumber: 'NPI',
  //   EmployementType: 'Employement Type',
  //   StartDate: 'Start Date',
  //   EndDate: 'End Date',
  //   SANum: 'SA Number',
  //   Units: 'Units',
  //   Service: 'Service',
  //   DiagnosisCode: 'Diagnosis Code',
  //   IFSP: 'IFSP',
  //   Location: 'Location',
  //   Sessions: 'Sessions',
  //   Duration: 'Duration',
  //   MakeupDays: 'Makeup Days',
  //   Provider: 'Provider'
};
